# Generated by Django 5.2.8 on 2025-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aluno_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopse'),
        ),
    ]
